name: Feature request
description: Suggest an improvement for docs, install flows, examples, or packaging.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        EN/RU accepted. Please keep requests concrete and scoped.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Install script (scripts/)
        - Documentation (docs/)
        - Examples (examples/)
        - Release packaging (releases/)
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see added/changed?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any workarounds or alternative ideas?
    validations:
      required: false

